/*
1- INTRODUÇÃO
    1.1- APRESENTAÇÃO PEDRA PEPEL TESOURA
    1.2- APRESENTAÇÃO TÍTULO
    1.3- APERTE ENTER PARA PROSSEGUIR
2- SELEÇÃO DE PERSONAGEM
3- SELEÇÃO DE TIPO DE JOGO
4- JOGO
5- FINALIZAÇÃO
*/